i understood the error it is because in runtime class dissappear from the serializefield
NullReferenceException: Object reference not set to an instance of an object
PrototypeProject.FPPTOTPP.FPPTOCPP () (at Assets/Scripts/Player Controls/FPPTOTPP.cs:68)
PrototypeProject.FPPTOTPP.Update () (at Assets/Scripts/Player Controls/FPPTOTPP.cs:92)